
platform :ios, '5.0'

# For regular projects
#pod 'NBUTableViewController'

# Optional for dynamic logging
#pod 'NBULog'

# Optional for on-device log console
#pod 'LumberjackConsole'

# For development
pod 'NBUTableViewController', :path => '../'

